services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: app-backend
    environment:
      - DATABASE_URL=sqlite+aiosqlite:////data/kbxy-dev.db
    volumes:
      - /Users/martinezdavid/Documents/MG/code/kbxy-monsters-pro/kbxy-dev.db:/data/kbxy-dev.db:rw
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/ || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: /api
    container_name: app-frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: unless-stopped