services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: kbxy-backend
    environment:
      - APP_ENV=dev
      - KBXY_DB_PATH=/app/data/kbxy-dev.db
      - KBXY_IMAGES_DIR=/app/images/monsters
      - SQLITE_BUSY_TIMEOUT_MS=4000
      - SQLITE_CONNECT_TIMEOUT_S=5
    volumes:
      - app_data:/app/data
      - app_images:/app/images
    ports:
      - "8000:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost:8000/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        VITE_API_BASE: /api
        VITE_MONSTER_IMG_BASE: /images/monsters
    container_name: kbxy-frontend
    ports:
      - "8080:80"
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped

volumes:
  app_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-data
  app_images:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./docker-data/images

networks:
  default:
    name: kbxy-network